framework:
    rate_limiter:
        password_reset:
            policy: 'fixed_window'
            limit: 3
            interval: '15 minutes'
        newsletter_subscribe:
            policy: 'fixed_window'
            limit: 3
            interval: '15 minutes'
        registration:
            policy: 'fixed_window'
            limit: 5
            interval: '15 minutes'
        activity_register:
            policy: 'fixed_window'
            limit: 10
            interval: '15 minutes'
        activity_proposal:
            policy: 'fixed_window'
            limit: 5
            interval: '1 hour'
