name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build image dev
        run: docker build --target dev --tag bac:dev .

      - name: Build image prod
        run: docker build --target prod --tag bac:prod .
